spring:
  application:
    name: ${SPRING_APP_NAME:eazybank-backend-app}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost:}${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

  config:
    activate:
      on-profile: prod

server:
  servlet:
    session:
      timeout: ${SESSION_TIME0UT:10m}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:error}

