spring:
  application:
    name: ${SPRING_APP_NAME:eazybank-backend-app}
#  security:
#    user:
#      name: ${SECURITY_NAME:uexcel}
#      password: ${SECURITY_PASSWORD:1234}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:trace}
