spring:
  application:
    name: ${SPRING_APP_NAME:eazybank-backend-app}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost:}${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}


#  security:
#    user:
#      name: ${SECURITY_NAME:uexcel}
#      password: ${SECURITY_PASSWORD:1234}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:trace}

